language: python
python:
  - "2.7"

install:
  - pip install tox

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34

script:
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: FI//lZjo1hx/t1treOa85vEWOn7bsaw7bCuKGUsoB8MuC+9QEuabyLDxdHQ6BoPMSIbWh95pVC+6OCXzr+NuWzF2syvarwfBl/Q2DqDx2CV2j+pYh6NKRoH22tZfyLua1POYGVyYrK6hyphlDyZScuKcBfSjQdIFsxU21EJgorw=
  on:
    tags: true
    repo: onefinestay/nameko-socket-server
